fix issues with rspec, removing sniffybara
  3) UploadsController behaves like an authenticating controller when being visited and submitting credentials outputs an error message if not successful
     Failure/Error: visit user_session_path

     Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

       ReferenceError: Can't find variable: Set
       ReferenceError: Can't find variable: Set
           at http://127.0.0.1:58010/packs-test/js/application-8ab2d686105b554977a1.js:35163
           at http://127.0.0.1:58010/packs-test/js/application-8ab2d686105b554977a1.js:35498 in ./node_modules/scheduler/cjs/scheduler-tracing.development.js
           at http://127.0.0.1:58010/packs-test/js/application-8ab2d686105b554977a1.js:20 in __webpack_require__
           at http://127.0.0.1:58010/packs-test/js/application-8ab2d686105b554977a1.js:36574 in ./node_modules/scheduler/tracing.js
           at http://127.0.0.1:58010/packs-test/js/application-8ab2d686105b554977a1.js:20 in __webpack_require__
           at http://127.0.0.1:58010/packs-test/js/application-8ab2d686105b554977a1.js:4581
           at http://127.0.0.1:58010/packs-test/js/application-8ab2d686105b554977a1.js:32258 in ./node_modules/react-dom/cjs/react-dom.development.js
           at http://127.0.0.1:58010/packs-test/js/application-8ab2d686105b554977a1.js:20 in __webpack_require__
           at http://127.0.0.1:58010/packs-test/js/application-8ab2d686105b554977a1.js:32301 in ./node_modules/react-dom/index.js
           at http://127.0.0.1:58010/packs-test/js/application-8ab2d686105b554977a1.js:20 in __webpack_require__
           at http://127.0.0.1:58010/packs-test/js/application-8ab2d686105b554977a1.js:34627 in ./node_modules/react_ujs/react_ujs/index.js
           at http://127.0.0.1:58010/packs-test/js/application-8ab2d686105b554977a1.js:20 in __webpack_require__
           at http://127.0.0.1:58010/packs-test/js/application-8ab2d686105b554977a1.js:118 in ./app/javascript/packs/application.js
           at http://127.0.0.1:58010/packs-test/js/application-8ab2d686105b554977a1.js:20 in __webpack_require__
           at http://127.0.0.1:58010/packs-test/js/application-8ab2d686105b554977a1.js:84
     Shared Example Group: "an authenticating controller" called from ./spec/controllers/uploads_controller_spec.rb:9
     # ./spec/controllers/shared_examples/shared_examples_for_authentication.rb:30:in `block (4 levels) in <top (required)>'